### ISSUE TITLE
How to train SB_MCL with the unsupervised classification setting?

### ISSUE THREAD

**Issue by Iranb** [soochan-lee/SB-MCL#1]
First,  thank you for sharing your code online. This paper has a solid foundation.

According to what is mentioned in the paper, SB_MCL is capable of supporting training for unsupervised classification tasks. 

Could you please tell me how this process is implemented in the code or which config i need to select to train omniglot dataset for unsupervised classification task?

**Comment by soochan-lee** [comment]
Sorry for the delayed response.

In the paper, we argued that SB-MCL supports both supervised and unsupervised learning. Classification serves as an example of a supervised learning task. For unsupervised learning, we conducted experiments on image generation.
